deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context mtbls/sd/metabolights-editor:famaladoss --namespace prod
    - kubectl config get-contexts