variables:
     VERSION: "2.0.0"
     BUILD_SCRIPTS_ROOT_PATH: "/home/gitlab-runner/ci_cd/k8s/metabolights-editor"
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging"
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - bash "$BUILD_SCRIPTS_ROOT_PATH/build.sh"

deploy_editor:
  stage: deploy
  only:
      - test
      - staging
      - master
  script:
    - bash "$BUILD_SCRIPTS_ROOT_PATH/deploy.sh"
