variables:
  APP_VERSION: "2.2.0"
  APPS_PROJECT_BRANCH_NAME: "${CI_COMMIT_REF_NAME}"
  BUILD_NUMBER: "${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}"
  IMAGE_TAG: "${APP_VERSION}-${CI_COMMIT_REF_NAME}"
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}:${IMAGE_TAG}"
  IMAGE_LATEST_TAG: "${CI_COMMIT_REF_NAME}-latest"
  LATEST_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-latest"
  CONFIG_DIR: "config-files"
workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging"
stages:
- build
- deploy
build_docker:
  stage: build
  image: docker:latest
  tags:
  - mtbls
  - docker
  script:
  - docker version
  - echo "APPS_PROJECT_URL $APPS_PROJECT_URL"
  - CURRENT_PATH="$(pwd)"
  - echo "CURRENT_PATH $CURRENT_PATH"
  - rm -rf $CONFIG_DIR
  - echo git clone https://$GITLAB_USER:$GITLAB_USER_TOKEN@${APPS_PROJECT_URL} $CONFIG_DIR
  - git clone https://$GITLAB_USER:$GITLAB_USER_TOKEN@${APPS_PROJECT_URL} $CONFIG_DIR
  - echo "CONFIG_DIR $CONFIG_DIR"
  - CICD_PROJECT_ROOT_PATH="$(realpath $CONFIG_DIR)"
  - cd $CONFIG_DIR
  - ls -al
  - echo checkout $APPS_PROJECT_BRANCH_NAME
  - git checkout $APPS_PROJECT_BRANCH_NAME
  - git status
  - git pull
  - export DOCKER_CONFIG=$(realpath $CICD_PROJECT_ROOT_PATH/$DOCKER_CONFIG_FILE_PATH)
  - cd $CURRENT_PATH
  - echo DOCKER_CONFIG $DOCKER_CONFIG
  - DEPLOYMENTS_FOLDER_SCRIPTS="$CICD_PROJECT_ROOT_PATH/$DEPLOYMENTS_FOLDER/scripts"
  - echo "DEPLOYMENTS_FOLDER_SCRIPTS $DEPLOYMENTS_FOLDER_SCRIPTS"
  - ls -al
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  - |-
    echo {\"version\": \"$APP_VERSION\", \"releaseName\": \"$BUILD_NUMBER\"} > src/assets/configs/version.json
  - cat src/assets/configs/version.json
  - echo "docker --config $DOCKER_CONFIG build -t $IMAGE_NAME ."
  - docker --config $DOCKER_CONFIG build -t $IMAGE_NAME .
  - echo "docker --config $DOCKER_CONFIG build --build-arg CONTAINER_REGISTRY_PREFIX=$CI_REGISTRY_IMAGE/ -t $LATEST_IMAGE_NAME ."
  - docker --config $DOCKER_CONFIG build --build-arg CONTAINER_REGISTRY_PREFIX=$CI_REGISTRY_IMAGE/ -t $LATEST_IMAGE_NAME .
  - docker --config $DOCKER_CONFIG push $IMAGE_NAME
  - docker --config $DOCKER_CONFIG push $LATEST_IMAGE_NAME

deploy_editor:
  stage: deploy
  image: k8s:1.23.17
  tags:
  - mtbls
  - docker
  variables:
    CHART_NAME: metabolights-editor
  rules:
  - if: $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "new-workflow" || $CI_COMMIT_BRANCH == "main-new-workflow"
    when: on_success
  - if: $CI_COMMIT_BRANCH == "main"
    when: manual
    allow_failure: true
  script:
  - apk add --no-cache git
  - echo "APPS_PROJECT_URL $APPS_PROJECT_URL"
  - CURRENT_PATH="$(pwd)"
  - echo "CURRENT_PATH $CURRENT_PATH"
  - rm -rf $CONFIG_DIR
  - echo git clone https://$GITLAB_USER:$GITLAB_USER_TOKEN@${APPS_PROJECT_URL} $CONFIG_DIR
  - git clone https://$GITLAB_USER:$GITLAB_USER_TOKEN@${APPS_PROJECT_URL} $CONFIG_DIR
  - echo "CONFIG_DIR $CONFIG_DIR"
  - CICD_PROJECT_ROOT_PATH="$(realpath $CONFIG_DIR)"
  - export K8S_CONFIG_FILE_PATH=$(realpath $CICD_PROJECT_ROOT_PATH/$K8S_CONFIG_FILE_PATH)
  - echo $K8S_CONFIG_FILE_PATH
  - cd $CONFIG_DIR
  - ls -al
  - echo checkout $APPS_PROJECT_BRANCH_NAME
  - git checkout $APPS_PROJECT_BRANCH_NAME
  - git status
  - git pull
  - DEPLOYMENTS_FOLDER_SCRIPTS="$CICD_PROJECT_ROOT_PATH/$DEPLOYMENTS_FOLDER/scripts"
  - echo "DEPLOYMENTS_FOLDER_SCRIPTS $DEPLOYMENTS_FOLDER_SCRIPTS"
  - ls -al
  - cd $DEPLOYMENTS_FOLDER_SCRIPTS
  - cat initial_setup.sh
  - bash initial_setup.sh
  - DEPLOYMENTS_CHART_PATH="$CICD_PROJECT_ROOT_PATH/$DEPLOYMENTS_FOLDER/charts/$CHART_NAME"
  - echo "DEPLOYMENTS_CHART_PATH $DEPLOYMENTS_CHART_PATH"
  - cd $DEPLOYMENTS_CHART_PATH
  - cat template.sh
  - echo template.sh "image.repository=$CI_REGISTRY_IMAGE,image.tag=$IMAGE_TAG"
  - bash template.sh "image.repository=$CI_REGISTRY_IMAGE,image.tag=$IMAGE_TAG"
  - cat install.sh
  - echo install.sh "image.repository=$CI_REGISTRY_IMAGE,image.tag=$IMAGE_TAG"
  - bash install.sh "image.repository=$CI_REGISTRY_IMAGE,image.tag=$IMAGE_TAG"
  - cd $CURRENT_PATH
  - rm -rf $CONFIG_DIR
