variables:
  VERSION: "2.2.0"
  BUILD_SCRIPTS_ROOT_PATH: "/home/gitlab-runner/ci_cd/k8s"
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
stages:
- build
- push
- deploy

checkout_configs:
  stage: build
  script:
  - bash "$BUILD_SCRIPTS_ROOT_PATH/checkout_configs.sh"

build_container:
  stage: build
  script:
  - bash "$BUILD_SCRIPTS_ROOT_PATH/metabolights-editor/build_container.sh"

push_container:
  stage: push
  script:
  - bash "$BUILD_SCRIPTS_ROOT_PATH/push_container.sh"