variables:
     VERSION: "2.0.0"
     BUILD_SCRIPTS_ROOT_PATH: "/home/gitlab-runner/ci_cd/standalone/editor"
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "test" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging"
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "development-pipeline-test"
      variables:
        CONFIGURAION_NAME: development
        RELEASE_NAME: dev.${CI_PIPELINE_ID}
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        CONFIGURAION_NAME: production
        RELEASE_NAME: ${CI_PIPELINE_ID}
    - if: $CI_COMMIT_BRANCH == "test"
      variables:
        CONFIGURAION_NAME: test
        RELEASE_NAME: test.${CI_PIPELINE_ID}
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        CONFIGURAION_NAME: staging
        RELEASE_NAME: staging.${CI_PIPELINE_ID}
stages:
  - build
  - configure
  - deploy

build:
  stage: build
  script:
    - bash "$BUILD_SCRIPTS_ROOT_PATH/build.sh"

deploy_editor:
  stage: deploy
  only:
      - test
      - staging
  script:
    - bash "$BUILD_SCRIPTS_ROOT_PATH/deploy.sh"
