ARG CONTAINER_REGISTRY_PREFIX=docker.io/

FROM ${CONTAINER_REGISTRY_PREFIX}nginx:1.28
LABEL maintainer="MetaboLights (metabolights-help @ ebi.ac.uk)"

COPY /dist /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8000

ENTRYPOINT ["nginx", "-g", "daemon off;"]
