export const SET_STUDY_IDENTIFIER = "SET_STUDY_IDENTIFIER";
export const SET_STUDY_TITLE = "SET_STUDY_TITLE";
export const SET_STUDY_ABSTRACT = "SET_STUDY_ABSTRACT";

export const SET_STUDY_SUBMISSION_DATE = "SET_STUDY_SUBMISSION_DATE";
export const SET_STUDY_RELEASE_DATE = "SET_STUDY_RELEASE_DATE";
export const SET_STUDY_STATUS = "SET_STUDY_STATUS";
export const SET_STUDY_REVIEWER_LINK = "SET_STUDY_REVIEWER_LINK";

export const SET_STUDY_PUBLICATIONS = "SET_STUDY_PUBLICATIONS";
export const UPDATE_STUDY_PUBLICATIONS = "UPDATE_STUDY_PUBLICATIONS";

export const SET_STUDY_PEOPLE = "SET_STUDY_PEOPLE";
export const UPDATE_STUDY_PEOPLE = "UPDATE_STUDY_PEOPLE";

export const LOAD_VALIDATION_RULES = "LOAD_VALIDATION_RULES";
export const SET_STUDY_DESIGN_DESCRIPTORS = "SET_STUDY_DESIGN_DESCRIPTORS";
export const UPDATE_STUDY_DESIGN_DESCRIPTORS =
  "UPDATE_STUDY_DESIGN_DESCRIPTORS";
export const SET_STUDY_FACTORS = "SET_STUDY_FACTORS";
export const SET_STUDY_ASSAYS = "SET_STUDY_ASSAYS";
export const SET_STUDY_ORGANISMS = "SET_STUDY_ORGANISMS";
export const SET_STUDY_PROTOCOLS = "SET_STUDY_PROTOCOLS";
export const UPDATE_STUDY_PROTOCOLS = "UPDATE_STUDY_PROTOCOLS";
export const UPDATE_STUDY_FACTORS = "UPDATE_STUDY_FACTORS";
export const SET_STUDY_SAMPLES = "SET_STUDY_SAMPLES";
export const SET_STUDY_PROCESS_SEQUENCE = "SET_STUDY_PROCESS_SEQUENCE";
export const ADD_STUDY_PROCESS_SEQUENCE = "ADD_STUDY_PROCESS_SEQUENCE";

export const ADD_STUDY_ASSAY = "ADD_STUDY_ASSAY";

export const ADD_MAF = "ADD_MAF";
export const UPDATE_MAF_DATA = "UPDATE_MAF_DATA";
export const ADD_STUDY_ASSAY_TABLE = "ADD_STUDY_ASSAY_TABLE";

export const SET_UPLOAD_LOCATION = "SET_UPLOAD_LOCATION";
export const SET_OBFUSCATION_CODE = "SET_OBFUSCATION_CODE";
export const SET_STUDY_VALIDATION = "SET_STUDY_VALIDATION";

export const SET_STUDY_FILES = "SET_STUDY_FILES";

export const SET_STUDY_ASSAY = "SET_STUDY_ASSAY";
export const DELETE_STUDY_ASSAY = "DELETE_STUDY_ASSAY";
export const SET_STUDY_MAF = "SET_STUDY_MAF";
export const SET_ASSAY_MAF = "SET_ASSAY_MAF";

export const SET_PROTOCOL_EXPAND = "SET_PROTOCOL_EXPAND";

export const SET_STUDY_ERROR = "SET_STUDY_ERROR";
export const SET_STUDY_READONLY = "SET_STUDY_READONLY";
